config/routes.rb
Rails.application.routes.draw do
  resources :cocktails
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail
  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show, :create]

  def index
    @cocktails = Cocktail.all
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    cocktail.save
  end

  def show
  end

  def destroy
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/views/cocktails/components/_cards.html.erb
<div class="card-product">
  <!-- <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" /> -->

  <%= image_tag "1.jpg", alt: "Le Wagon", width: 200 %>
  <div class="card-product-infos">
    <h2><%= cocktail.name %></h2>
    <p>Product description with <strong>relevant info</strong> only.</p>
  </div>
</div>

app/views/cocktails/components/_navbar.html.erb
<div class="home-banner">
  <h1>Le Wagon</h1>
</div>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-6">
      <%= "Lorem ipsum dolor sit amet, consectetur adipisicing elit " * 100 %>
    </div>
  </div>
</div>

app/views/cocktails/components/avatar.html.erb
<%= image_tag "4.jpg", class: "avatar", alt: "avatar" %>

app/views/cocktails/index.html.erb
<h1>Cocktails</h1>


<% @cocktails.each do |cocktail| %>
<%= render 'cocktails/components/cards', cocktail: cocktail %>
<p><%= cocktail.name %></p>
   <%= button_to 'Delete', cocktail_path(cocktail),
    method: :delete,
    data: { confirm: 'Are you sure' } %>
<% end %>

app/views/cocktails/new.html.erb
<h1>Cocktails New</h1>


<%= simple_form_for @cocktail do |f| %>
  <%= f.input :name %>
  <%= f.button :submit %>
<% end %>

app/views/cocktails/show.html.erb
<h1>Cocktails</h1>

<%= @cocktail.name %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
    <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </head>


  <body>
    <div class="container">
    <%= yield %>


    </div>
  </body>

</html>